--load setting plugins
require'setting.plugins.cmp'
require'setting.plugins.lsp'
require'setting.plugins.tree'
require'setting.plugins.alpha'
require'setting.plugins.feline'
require'setting.plugins.comment'
require'setting.plugins.gitsings'
require'setting.plugins.telescope'
require'setting.plugins.tokyonight'
require'setting.plugins.treesitter'
require'setting.plugins.bufferline'
